const ActionTypes = {
  SEARCH_REPOS: 'SEARCH_REPOS',
  ADD_BOOKMARK: 'ADD_BOOKMARK',
  MOVE_BOOKMARK: 'MOVE_BOOKMARK',
  DELETE_BOOKMARK: 'DELETE_BOOKMARK',
  ADD_BOOKMARK_LIST: 'ADD_BOOKMARK_LIST',
  DELETE_BOOKMARK_LIST: 'DELETE_BOOKMARK_LIST',
}

export default ActionTypes;
